[default.extend-words]
somme = "somme"
classe = "classe"
sur = "sur"
fonction = "fonction"
normale = "normale"
thm = "thm"

[type.cpp.extend-words]
ba = "ba"

[type.lean.extend-words]
hpe = "hpe"
hge = "hge"
