// Validate a candidate g-extra cut generated by the full radius-one Star.
//
// This proves only an upper bound: if the post-deletion component test passes,
// it establishes kappa_g(A(n,k)) <= |N(S)|. It does not prove optimality.
// Usage: validate_extra_cut [n k] [--json]
// Default output is a concise human-readable report; --json emits strict JSON.

#include <algorithm>
#include <iostream>
#include <numeric>
#include <queue>
#include <string>
#include <vector>

struct ArrangementGraph {
    int n;
    int k;
    std::vector<int> status; // -1 invalid, 0 surviving, 1 S, 2 N(S), 3 visited
    std::vector<std::vector<int>> valid_vertices;
    std::vector<int> flat_index;

    ArrangementGraph(int n_value, int k_value) : n(n_value), k(k_value) {
        int capacity = 1;
        for (int i = 0; i < k; ++i)
            capacity *= n;
        status.assign(capacity, -1);
        flat_index.assign(capacity, -1);

        std::vector<int> prefix;
        std::vector<bool> used(n, false);
        generate_valid(prefix, used);
    }

    int encode(const std::vector<int> &vertex) const {
        return std::accumulate(vertex.begin(), vertex.end(), 0,
                               [this](const int code, const int symbol) {
                                   return code * n + symbol;
                               });
    }

    void generate_valid(std::vector<int> &prefix, std::vector<bool> &used) {
        if (static_cast<int>(prefix.size()) == k) {
            const int code = encode(prefix);
            status[code] = 0;
            flat_index[code] = static_cast<int>(valid_vertices.size());
            valid_vertices.push_back(prefix);
            return;
        }
        for (int symbol = 0; symbol < n; ++symbol) {
            if (used[symbol])
                continue;
            used[symbol] = true;
            prefix.push_back(symbol);
            generate_valid(prefix, used);
            prefix.pop_back();
            used[symbol] = false;
        }
    }

    std::vector<int> encoded_neighbors(const std::vector<int> &vertex) const {
        std::vector<int> result;
        std::vector<bool> used(n, false);
        for (const int symbol : vertex)
            used[symbol] = true;

        result.reserve(k * (n - k));
        for (int position = 0; position < k; ++position) {
            for (int symbol = 0; symbol < n; ++symbol) {
                if (used[symbol])
                    continue;
                std::vector<int> neighbor = vertex;
                neighbor[position] = symbol;
                result.push_back(encode(neighbor));
            }
        }
        return result;
    }
};

bool connected(const ArrangementGraph &graph,
               const std::vector<std::vector<int>> &subset) {
    if (subset.empty())
        return true;

    std::vector<bool> visited(subset.size(), false);
    std::queue<int> pending;
    pending.push(0);
    visited[0] = true;
    int reached = 1;

    while (!pending.empty()) {
        const int index = pending.front();
        pending.pop();
        const std::vector<int> neighbors =
            graph.encoded_neighbors(subset[index]);
        for (size_t candidate = 0; candidate < subset.size(); ++candidate) {
            if (visited[candidate])
                continue;
            const int code = graph.encode(subset[candidate]);
            if (std::find(neighbors.begin(), neighbors.end(), code) ==
                neighbors.end())
                continue;
            visited[candidate] = true;
            pending.push(static_cast<int>(candidate));
            ++reached;
        }
    }
    return reached == static_cast<int>(subset.size());
}

void print_json_array(std::ostream &out, const std::vector<int> &values) {
    out << '[';
    for (size_t i = 0; i < values.size(); ++i) {
        if (i != 0)
            out << ',';
        out << values[i];
    }
    out << ']';
}

void dump_json(std::ostream &out, const ArrangementGraph &graph,
               const std::vector<std::vector<int>> &star,
               const std::vector<int> &boundary_codes,
               const std::vector<int> &component_sizes, int g, bool valid) {
    const int m = graph.n - graph.k;
    const int degree = graph.k * m;
    const int family_a = graph.k * (graph.k - 1) * m;
    const int family_b = graph.k * (graph.k - 1) / 2 * m * (m - 1);
    out << "{\n  \"graph\": {\"n\": " << graph.n << ", \"k\": " << graph.k
        << ", \"m\": " << m << ", \"degree\": " << degree
        << "},\n  \"cut_properties\": {\"g\": " << g
        << ", \"target_volume\": " << star.size()
        << ", \"actual_boundary\": " << boundary_codes.size()
        << ", \"valid\": " << (valid ? "true" : "false") << "},\n";
    out << "  \"center_vertex\": ";
    print_json_array(out, star.front());
    out << ",\n  \"spare_symbols\": [";
    for (int symbol = graph.k; symbol < graph.n; ++symbol) {
        if (symbol != graph.k)
            out << ',';
        out << symbol;
    }
    out << "],\n  \"star\": {\n"
        << "    \"size\": " << star.size()
        << ", \"rule\": \"one coordinate replaced by one spare symbol\",\n"
        << "    \"internal_edges\": " << graph.k * (m + 1) * m / 2
        << ",\n    \"degree_sequence\": {\"center\": " << degree
        << ", \"leaves\": " << m << ", \"leaf_count\": " << graph.k * m
        << "}\n  },\n";
    out << "  \"cut\": {\"size\": " << boundary_codes.size()
        << ", \"families\": [\n"
        << "    {\"type\": \"internal_shift\", \"pattern\": "
           "\"c[i<-s,j<-i]\", \"count\": "
        << family_a << ", \"multiplicity\": 1},\n"
        << "    {\"type\": \"double_spare\", \"pattern\": "
           "\"c[i<-s,j<-t]\", \"count\": "
        << family_b << ", \"multiplicity\": 2}\n  ]},\n";
    out << "  \"component_sizes\": [";
    for (size_t i = 0; i < component_sizes.size(); ++i) {
        if (i != 0)
            out << ',';
        out << component_sizes[i];
    }
    out << "]\n}\n";
}

int main(int argc, char **argv) {
    int n = 11;
    int k = 6;
    bool json_output = false;
    int positional = 0;
    for (int arg = 1; arg < argc; ++arg) {
        const std::string value = argv[arg];
        if (value == "-h" || value == "--help") {
            std::cout << "Usage: " << argv[0] << " [n k] [--json]\n";
            return 0;
        }
        if (value == "--json") {
            json_output = true;
            continue;
        }
        if (value.rfind("--", 0) == 0) {
            std::cerr << "Error: unknown option '" << value << "'.\n";
            return 1;
        }
        if (positional == 0)
            n = std::stoi(value);
        else if (positional == 1)
            k = std::stoi(value);
        else {
            std::cerr << "Usage: " << argv[0] << " [n k] [--json]\n";
            return 1;
        }
        ++positional;
    }
    if (n <= k || k < 1) {
        std::cerr << "Error: require n > k >= 1.\n";
        return 1;
    }
    const bool show_progress = !json_output;

    if (show_progress)
        std::cout << "Building A(" << n << ',' << k << ")...\n";
    ArrangementGraph graph(n, k);
    if (show_progress)
        std::cout << "Total valid vertices: " << graph.valid_vertices.size()
                  << "\n";

    std::vector<int> center(k);
    std::iota(center.begin(), center.end(), 0);
    std::vector<std::vector<int>> star{center};
    graph.status[graph.encode(center)] = 1;
    for (int position = 0; position < k; ++position) {
        for (int symbol = k; symbol < n; ++symbol) {
            std::vector<int> leaf = center;
            leaf[position] = symbol;
            star.push_back(leaf);
            graph.status[graph.encode(leaf)] = 1;
        }
    }

    const int g = static_cast<int>(star.size()) - 1;
    if (show_progress) {
        std::cout << "\nCandidate g = " << g << "\n";
        std::cout << "|S| = " << star.size() << "\n";
    }
    if (!connected(graph, star)) {
        std::cerr << "Error: constructed Star is not connected.\n";
        return 1;
    }
    if (show_progress)
        std::cout << "Subset S connectivity verified.\n";

    int boundary_count = 0;
    std::vector<int> boundary_codes;
    for (const auto &vertex : star) {
        for (const int neighbor : graph.encoded_neighbors(vertex)) {
            if (graph.status[neighbor] != 0)
                continue;
            graph.status[neighbor] = 2;
            boundary_codes.push_back(neighbor);
            ++boundary_count;
        }
    }
    if (show_progress)
        std::cout << "|N(S)| = " << boundary_count << "\n";
    if (n == 11 && k == 6 && boundary_count != 450) {
        std::cerr << "Error: expected |N(S)| = 450 for A(11,6), got "
                  << boundary_count << ".\n";
        return 1;
    }

    if (show_progress)
        std::cout << "Validating " << g << "-extra cut properties...\n";
    std::vector<int> component_sizes;
    for (const auto &vertex : graph.valid_vertices) {
        const int start = graph.encode(vertex);
        if (graph.status[start] != 0 && graph.status[start] != 1)
            continue;

        int size = 0;
        std::queue<int> pending;
        pending.push(start);
        graph.status[start] = 3;
        while (!pending.empty()) {
            const int current = pending.front();
            pending.pop();
            ++size;
            const auto &current_vertex =
                graph.valid_vertices[graph.flat_index[current]];
            for (const int neighbor : graph.encoded_neighbors(current_vertex)) {
                if (graph.status[neighbor] != 0 && graph.status[neighbor] != 1)
                    continue;
                graph.status[neighbor] = 3;
                pending.push(neighbor);
            }
        }
        component_sizes.push_back(size);
    }

    std::sort(component_sizes.begin(), component_sizes.end());
    if (show_progress)
        std::cout << "component sizes after deletion:\n";
    bool valid = component_sizes.size() >= 2;
    for (const int size : component_sizes) {
        if (show_progress)
            std::cout << "  " << size << '\n';
        if (size <= g)
            valid = false;
    }

    if (!valid) {
        if (json_output) {
            dump_json(std::cout, graph, star, boundary_codes, component_sizes,
                      g, false);
        } else {
            std::cout << "valid " << g << "-extra cut: no\n";
        }
        return 0;
    }
    if (json_output) {
        dump_json(std::cout, graph, star, boundary_codes, component_sizes, g,
                  true);
    } else {
        std::cout << "valid " << g << "-extra cut: yes\n";
        std::cout << "therefore kappa_" << g << "(A(" << n << ',' << k
                  << ")) <= " << boundary_count << "\n";
    }
    return 0;
}
