// Validate a candidate g-extra cut generated by the full radius-one Star.
//
// This proves only an upper bound: if the post-deletion component test passes,
// it establishes kappa_g(A(n,k)) <= |N(S)|. It does not prove optimality.
// Usage: validate_extra_cut [n k] [--json] [--screen]
// Default output is a concise human-readable report; --json emits strict JSON.
// `--screen` performs only the arithmetic Star/Hamming comparison.

#include <algorithm>
#include <array>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numeric>
#include <queue>
#include <string>
#include <vector>

struct ArrangementGraph {
    int n;
    int k;
    std::vector<std::uint8_t>
        status; // 255 invalid, 0 surviving, 1 S, 2 N(S), 3 visited
    std::size_t valid_count = 0;
    std::vector<std::uint64_t> place;

    ArrangementGraph(int n_value, int k_value) : n(n_value), k(k_value) {
        std::uint64_t capacity = 1;
        for (int i = 0; i < k; ++i)
            capacity *= static_cast<std::uint64_t>(n);
        status.assign(capacity, 255);
        place.assign(k, 1);
        for (int position = k - 2; position >= 0; --position)
            place[position] = place[position + 1] * static_cast<std::uint64_t>(n);

        std::vector<int> prefix;
        std::vector<bool> used(n, false);
        generate_valid(prefix, used);
    }

    std::uint64_t encode(const std::vector<int> &vertex) const {
        return std::accumulate(
            vertex.begin(), vertex.end(), std::uint64_t{0},
            [this](const std::uint64_t code, const int symbol) {
                return code * static_cast<std::uint64_t>(n) + symbol;
            });
    }

    void generate_valid(std::vector<int> &prefix, std::vector<bool> &used) {
        if (static_cast<int>(prefix.size()) == k) {
            const std::uint64_t code = encode(prefix);
            status[code] = 0;
            ++valid_count;
            return;
        }
        for (int symbol = 0; symbol < n; ++symbol) {
            if (used[symbol])
                continue;
            used[symbol] = true;
            prefix.push_back(symbol);
            generate_valid(prefix, used);
            prefix.pop_back();
            used[symbol] = false;
        }
    }

    template <typename Function>
    void enumerate_valid(int depth, std::uint64_t code,
                         std::vector<unsigned char> &used,
                         Function &function) const {
        if (depth == k) {
            function(code);
            return;
        }
        for (int symbol = 0; symbol < n; ++symbol) {
            if (used[symbol])
                continue;
            used[symbol] = 1;
            enumerate_valid(depth + 1, code + symbol * place[depth], used,
                            function);
            used[symbol] = 0;
        }
    }

    template <typename Function>
    void for_each_valid_code(Function function) const {
        std::vector<unsigned char> used(n, 0);
        enumerate_valid(0, 0, used, function);
    }

    template <typename Function>
    void for_each_neighbor(std::uint64_t code, Function function) const {
        std::array<unsigned char, 256> used{};
        for (int position = 0; position < k; ++position) {
            const int symbol = static_cast<int>((code / place[position]) % n);
            used[symbol] = 1;
        }
        for (int position = 0; position < k; ++position) {
            const int current = static_cast<int>((code / place[position]) % n);
            for (int symbol = 0; symbol < n; ++symbol) {
                if (used[symbol])
                    continue;
                function(code + (symbol - current) * place[position]);
            }
        }
    }
};

bool connected(const ArrangementGraph &graph,
               const std::vector<std::uint64_t> &subset) {
    if (subset.empty())
        return true;

    std::vector<bool> visited(subset.size(), false);
    std::queue<std::uint64_t> pending;
    pending.push(subset[0]);
    visited[0] = true;
    int reached = 1;

    while (!pending.empty()) {
        const std::uint64_t code = pending.front();
        pending.pop();
        graph.for_each_neighbor(code, [&](const std::uint64_t neighbor) {
            if (graph.status[neighbor] == 1) {
                for (size_t candidate = 0; candidate < subset.size();
                     ++candidate) {
                    if (!visited[candidate] && subset[candidate] == neighbor) {
                        visited[candidate] = true;
                        pending.push(neighbor);
                        ++reached;
                    }
                }
            }
        });
    }
    return reached == static_cast<int>(subset.size());
}

std::uint64_t flat_code_space(int n, int k, bool &overflow) {
    overflow = false;
    std::uint64_t capacity = 1;
    for (int i = 0; i < k; ++i) {
        if (n > 0 && capacity > std::numeric_limits<std::uint64_t>::max() /
                                    static_cast<std::uint64_t>(n)) {
            overflow = true;
            return std::numeric_limits<std::uint64_t>::max();
        }
        capacity *= static_cast<std::uint64_t>(n);
    }
    return capacity;
}

long long defect_sum(int r) {
    long long result = 0;
    for (int i = 0; i < r; ++i)
        result += __builtin_popcount(static_cast<unsigned>(i));
    return result;
}

int bit_length(int value) {
    int result = 0;
    while (value > 0) {
        ++result;
        value >>= 1;
    }
    return result;
}

long long collision_constant(int r) {
    if (r == 0)
        return 0;
    long long result = r - 1 - defect_sum(r);
    for (int i = 1; i < r; ++i)
        result += bit_length(i);
    return result;
}

void print_json_array(std::ostream &out, const std::vector<int> &values) {
    out << '[';
    for (size_t i = 0; i < values.size(); ++i) {
        if (i != 0)
            out << ',';
        out << values[i];
    }
    out << ']';
}

void dump_json(std::ostream &out, const ArrangementGraph &graph,
               const std::vector<int> &center,
               const std::vector<std::uint64_t> &star,
               const std::vector<std::uint64_t> &boundary_codes,
               const std::vector<int> &component_sizes, int g, bool valid,
               int d, bool embedding_gate, long long hamming_boundary,
               const std::string &classification) {
    const int m = graph.n - graph.k;
    const int degree = graph.k * m;
    const int family_a = graph.k * (graph.k - 1) * m;
    const int family_b = graph.k * (graph.k - 1) / 2 * m * (m - 1);
    out << "{\n  \"graph\": {\"n\": " << graph.n << ", \"k\": " << graph.k
        << ", \"m\": " << m << ", \"degree\": " << degree
        << ", \"valid_vertices\": " << graph.valid_count
        << "},\n  \"cut_properties\": {\"g\": " << g
        << ", \"R\": " << star.size() << ", \"target_volume\": " << star.size()
        << ", \"actual_boundary\": " << boundary_codes.size()
        << ", \"valid\": " << (valid ? "true" : "false") << "},\n"
        << "  \"hamming_comparison\": {\"d\": " << d
        << ", \"embedding_gate\": " << (embedding_gate ? "true" : "false")
        << ", \"star_boundary\": " << boundary_codes.size()
        << ", \"hamming_boundary\": " << hamming_boundary
        << ", \"classification\": \"" << classification << "\"},\n";
    out << "  \"deep_check\": \"completed\",\n";
    out << "  \"center_vertex\": ";
    print_json_array(out, center);
    out << ",\n  \"spare_symbols\": [";
    for (int symbol = graph.k; symbol < graph.n; ++symbol) {
        if (symbol != graph.k)
            out << ',';
        out << symbol;
    }
    out << "],\n  \"star\": {\n"
        << "    \"size\": " << star.size()
        << ", \"rule\": \"one coordinate replaced by one spare symbol\",\n"
        << "    \"internal_edges\": " << graph.k * (m + 1) * m / 2
        << ",\n    \"degree_sequence\": {\"center\": " << degree
        << ", \"leaves\": " << m << ", \"leaf_count\": " << graph.k * m
        << "}\n  },\n";
    out << "  \"cut\": {\"size\": " << boundary_codes.size()
        << ", \"families\": [\n"
        << "    {\"type\": \"internal_shift\", \"pattern\": "
           "\"c[i<-s,j<-i]\", \"count\": "
        << family_a << ", \"multiplicity\": 1},\n"
        << "    {\"type\": \"double_spare\", \"pattern\": "
           "\"c[i<-s,j<-t]\", \"count\": "
        << family_b << ", \"multiplicity\": 2}\n  ]},\n";
    out << "  \"component_sizes\": [";
    for (size_t i = 0; i < component_sizes.size(); ++i) {
        if (i != 0)
            out << ',';
        out << component_sizes[i];
    }
    out << "]\n}\n";
}

void dump_skipped_json(std::ostream &out, int n, int k, std::size_t valid_count,
                       int g, int volume, int degree, int d,
                       bool embedding_gate, long long star_boundary,
                       long long hamming_boundary,
                       const std::string &classification) {
    out << "{\n  \"graph\": {\"n\": " << n << ", \"k\": " << k
        << ", \"m\": " << n - k << ", \"degree\": " << degree
        << ", \"valid_vertices\": " << valid_count << "},\n"
        << "  \"cut_properties\": {\"g\": " << g << ", \"R\": " << volume
        << ", \"target_volume\": " << volume
        << ", \"actual_boundary\": " << star_boundary << "},\n"
        << "  \"hamming_comparison\": {\"d\": " << d
        << ", \"embedding_gate\": " << (embedding_gate ? "true" : "false")
        << ", \"star_boundary\": " << star_boundary
        << ", \"hamming_boundary\": " << hamming_boundary
        << ", \"classification\": \"" << classification << "\"},\n"
        << "  \"deep_check\": \"skipped\",\n"
        << "  \"valid\": null,\n  \"component_sizes\": null\n}\n";
}

int main(int argc, char **argv) {
    int n = 11;
    int k = 6;
    bool json_output = false;
    bool screen_only = false;
    int positional = 0;
    for (int arg = 1; arg < argc; ++arg) {
        const std::string value = argv[arg];
        if (value == "-h" || value == "--help") {
            std::cout << "Usage: " << argv[0] << " [n k] [--json] [--screen]\n";
            return 0;
        }
        if (value == "--json") {
            json_output = true;
            continue;
        }
        if (value == "--screen") {
            screen_only = true;
            continue;
        }
        if (value.rfind("--", 0) == 0) {
            std::cerr << "Error: unknown option '" << value << "'.\n";
            return 1;
        }
        if (positional == 0)
            n = std::stoi(value);
        else if (positional == 1)
            k = std::stoi(value);
        else {
            std::cerr << "Usage: " << argv[0] << " [n k] [--json] [--screen]\n";
            return 1;
        }
        ++positional;
    }
    if (n <= k || k < 1) {
        if (!json_output) {
            std::cout << "Building A(" << n << ',' << k << ")...\n";
            bool overflow = false;
            const std::uint64_t capacity = flat_code_space(n, k, overflow);
            std::cout << "Would require flat code space: " << n << '^' << k
                      << " = ";
            if (overflow)
                std::cout << ">=";
            std::cout << capacity << " slots\n";
        }
        std::cerr << "Error: require n > k >= 1.\n";
        return 1;
    }
    const bool show_progress = !json_output;

    const int m = n - k;
    const int degree = k * m;
    const int volume = 1 + degree;
    const int g = volume - 1;
    std::size_t valid_count = 1;
    for (int position = 0; position < k; ++position)
        valid_count *= static_cast<std::size_t>(n - position);
    const long long star_boundary =
        static_cast<long long>(k) * (k - 1) * m +
        static_cast<long long>(k) * (k - 1) / 2 * m * (m - 1);
    const int d = bit_length(volume - 1);
    const bool embedding_gate = d <= k && d <= m;
    const long long hamming_potential =
        collision_constant(volume) +
        static_cast<long long>(m) * defect_sum(volume);
    const long long hamming_boundary =
        static_cast<long long>(volume) * degree - hamming_potential;
    std::string arithmetic_classification;
    if (star_boundary < hamming_boundary && embedding_gate)
        arithmetic_classification = "HARD COUNTEREXAMPLE: RestrictedLowerBound";
    else if (star_boundary < hamming_boundary)
        arithmetic_classification =
            "SOFT COUNTEREXAMPLE: UniversalLowerBound only";
    else
        arithmetic_classification = "SATISFIES HAMMING OPTIMALITY";

    if (screen_only) {
        if (json_output) {
            dump_skipped_json(std::cout, n, k, valid_count, g, volume, degree,
                              d, embedding_gate, star_boundary,
                              hamming_boundary, arithmetic_classification);
        } else {
            std::cout << "A(" << n << ',' << k << ") arithmetic screening\n"
                      << "R = " << volume << ", g = " << g
                      << ", Star boundary = " << star_boundary
                      << ", Hamming baseline = " << hamming_boundary << '\n'
                      << "Deep check: skipped\n"
                      << arithmetic_classification << '\n';
            std::cout << '\n';
        }
        return 0;
    }

    // A(14,8) needs 14^8 = 1,475,789,056 one-byte status slots.  Keep a
    // finite guard, but do not reject that useful boundary case outright.
    constexpr std::uint64_t max_code_space =
        std::numeric_limits<std::uint32_t>::max();
    bool code_space_overflow = false;
    const std::uint64_t code_space = flat_code_space(n, k, code_space_overflow);
    if (code_space_overflow || code_space > max_code_space) {
        std::cerr << "Error: A(" << n << ',' << std::setw(2) << k
                  << ") needs too much flat code space (n^k = ";
        if (code_space_overflow)
            std::cerr << ">=";
        std::cerr << code_space << " slots; guard = " << max_code_space
                  << ").\n";
        return 1;
    }

    if (show_progress)
        std::cout << "Building A(" << n << ',' << k << ")...\n";
    ArrangementGraph graph(n, k);
    if (show_progress)
        std::cout << "Total valid vertices: " << graph.valid_count << "\n";

    std::vector<int> center(k);
    std::iota(center.begin(), center.end(), 0);
    const std::uint64_t center_code = graph.encode(center);
    std::vector<std::uint64_t> star{center_code};
    graph.status[center_code] = 1;
    for (int position = 0; position < k; ++position) {
        for (int symbol = k; symbol < n; ++symbol) {
            const std::uint64_t leaf =
                center_code +
                (symbol - center[position]) * graph.place[position];
            star.push_back(leaf);
            graph.status[leaf] = 1;
        }
    }

    if (show_progress) {
        std::cout << "R = " << volume << "\n";
        std::cout << "Candidate g = " << g << "\n";
        std::cout << "|S| = " << star.size() << "\n";
    }
    if (!connected(graph, star)) {
        std::cerr << "Error: constructed Star is not connected.\n";
        return 1;
    }
    if (show_progress)
        std::cout << "Subset S connectivity verified.\n";

    int boundary_count = 0;
    std::vector<std::uint64_t> boundary_codes;
    for (const std::uint64_t vertex : star) {
        graph.for_each_neighbor(vertex, [&](const std::uint64_t neighbor) {
            if (graph.status[neighbor] != 0)
                return;
            graph.status[neighbor] = 2;
            boundary_codes.push_back(neighbor);
            ++boundary_count;
        });
    }
    if (show_progress)
        std::cout << "|N(S)| = " << boundary_count << "\n";
    if (n == 11 && k == 6 && boundary_count != 450) {
        std::cerr << "Error: expected |N(S)| = 450 for A(11,6), got "
                  << boundary_count << ".\n";
        return 1;
    }
    if (static_cast<long long>(boundary_count) != star_boundary) {
        std::cerr << "Error: closed-form Star boundary disagrees with "
                  << "enumeration (formula " << star_boundary << ", got "
                  << boundary_count << ").\n";
        return 1;
    }

    if (show_progress)
        std::cout << "Validating " << g << "-extra cut properties...\n";
    std::vector<int> component_sizes;
    graph.for_each_valid_code([&](const std::uint64_t start) {
        if (graph.status[start] != 0 && graph.status[start] != 1)
            return;

        int size = 0;
        std::queue<std::uint64_t> pending;
        pending.push(start);
        graph.status[start] = 3;
        while (!pending.empty()) {
            const std::uint64_t current = pending.front();
            pending.pop();
            ++size;
            graph.for_each_neighbor(current, [&](const std::uint64_t neighbor) {
                if (graph.status[neighbor] != 0 && graph.status[neighbor] != 1)
                    return;
                graph.status[neighbor] = 3;
                pending.push(neighbor);
            });
        }
        component_sizes.push_back(size);
    });

    std::sort(component_sizes.begin(), component_sizes.end());
    if (show_progress)
        std::cout << "component sizes after deletion:\n";
    bool valid = component_sizes.size() >= 2;
    for (const int size : component_sizes) {
        if (show_progress)
            std::cout << "  " << size << '\n';
        if (size <= g)
            valid = false;
    }

    std::string classification = arithmetic_classification;

    if (!valid) {
        classification = "INVALID EXTRA CUT";
        if (json_output) {
            dump_json(std::cout, graph, center, star, boundary_codes,
                      component_sizes, g, false, d, embedding_gate,
                      hamming_boundary, classification);
        } else {
            std::cout << "valid " << g << "-extra cut: no\n";
            std::cout << classification << "\n";
            std::cout << '\n';
        }
        return 0;
    }
    if (json_output) {
        dump_json(std::cout, graph, center, star, boundary_codes,
                  component_sizes, g, true, d, embedding_gate, hamming_boundary,
                  classification);
    } else {
        std::cout << "valid " << g << "-extra cut: yes\n";
        std::cout << "therefore kappa_" << g << "(A(" << n << ',' << k
                  << ")) <= " << boundary_count << "\n";
        if (classification.find("COUNTEREXAMPLE") != std::string::npos) {
            std::cout << "Hamming baseline: " << hamming_boundary
                      << "; Star boundary: " << boundary_count << "\n";
            std::cout << "Embedding gate: d = " << d << ", k = " << k
                      << ", n-k = " << n - k << " ("
                      << (embedding_gate ? "open" : "closed") << ")\n";
        }
        std::cout << classification << "\n";
        std::cout << '\n';
    }
    return 0;
}
